version: '3'

services:
  dcs-download:
    image: download:v4
    container_name: dcs-download
    user: root
    ports:
      - "8090:8090"
    command: ./main
    #tty: true
    volumes:
      - "./dcs-download/download:/download"
      - "./dcs-download/config/config.yaml:/config/config.yaml"
  sftp-debug:
    image: atmoz/sftp
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:22"
    command: ossftp:oss123:1001::/
    volumes:
        - ./sftp-debug:/home/ossftp/var/opt/ericsson/
  kdb:
    image: timestored/kdb:latest
    ports:
      - "5006:5000"
    volumes:
      - ./kdb/start.q:/app/start.q
    command: q /app/start.q